### ISSUE TITLE
(BUG) Cannot deploy netstat

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/deployment-azure#32]
Template validation error
```
The template deployment 'Microsoft.Template' is not valid according to the validation procedure. 
The tracking id is 'c3be9485-654e-4f6c-a006-a369173540de'. See inner errors for details. 
Please see https://aka.ms/arm-deploy for usage details. (Code: InvalidTemplateDeployment)
```

**Comment by rstormsf** [comment]
Looks like I hit the limit in azure account.

**Comment by rstormsf** [comment]
<img width="434" alt="screen shot 2017-11-22 at 8 22 21 pm" src="https://user-images.githubusercontent.com/9360827/33158923-e26e4246-cfc2-11e7-815c-567ceb905942.png">

**Comment by phahulin** [comment]
Error looks like the link here
https://github.com/oraclesorg/deployment-azure/blob/dev-mainnet/nodes/netstats-server/template.json#L234
was leading to a non-existing page. I understand it's fixed now and netstats is deployed
