### ISSUE TITLE
(Feature) Remove repo hardcoded owner from scripts

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/deployment-azure#33]
https://github.com/oraclesorg/deployment-azure/blob/dev-mainnet/nodes/netstats-server/install.sh#L22

https://github.com/oraclesorg/deployment-azure/blob/dev-mainnet/nodes/netstats-server/install.sh#L41

I'd like to have a variable, not hardcoded `oraclesorg` in the scripts so I can use my own fork

Also
Owner of insta-mined coins should not be hardcoded:

https://github.com/oraclesorg/deployment-azure/blob/dev-mainnet/nodes/netstats-server/install.sh#L122

**Comment by phahulin** [comment]
Resolved by https://github.com/oraclesorg/deployment-azure/pull/34
