### ISSUE TITLE
Patent rights

### ISSUE THREAD

**Issue by IlyaGazman** [poanetwork/deployment-azure#39]
Hey guys,

It seems that your idea of Proof of authority conflicts with my pending patent application on Royal Network.

We both concluded that small networks would perform better than peer to peer. I saw that this idea hadn't been officialized, standardized or anyhow formalized, and so I filed for it, among other senses of my Confidence Coin blockchain.

While I choose to implement the selection of the peers by their mining power, in Royal Network only those who mined a block can join the network, I did offer several alternatives to the selection process in my application.

As I said it is just in a pending stage and it's not a patent yet, but it will be. 

So FYI guys.

Best,
Ilya Gazman
confidence-coin.com

**Comment by igorbarinov** [comment]
Ilya, good luck with your project. For legal inquiries feel free to contact our counselor at info@poa.net
